## Implementing Perceptron
#### Adapted from the learning materials provided by: ineuron.ai

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import joblib 
from matplotlib.colors import ListedColormap

In [6]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4 # initialze small weights
        print(f"initial weights before training: \n{self.weights}")
        self.eta = eta # learning rate
        self.epochs = epochs # number of epochs


    def activationFunction(self, inputs, weights):
        """
        Determines the activation of a neuron using a step function.
        Calculates Z where Z = w2.x2 + w1.x1 + w0.x0 = W*X

        Args:
            inputs: x (with bias)
            weights: w

        Returns:
            0: if z is less than 1
            1: if z is greater than 1
        """
        z = np.dot(inputs, weights) 
        return np.where(z > 0, 1, 0) 

    def fit(self, X, y):
        """
        Updates the weights to minimise loss through forward and back propagation.

        Args:
            X: input
            y: target
        """
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # concatinate with -1s
        print(f"X with bias: \n{X_with_bias}")

        for epoch in range(self.epochs):
            print("--" * 10)
            print(f"for epoch: {epoch}")
            print("--" * 10)

            y_hat = self.activationFunction(X_with_bias, self.weights) # foward propagation
            print(f"predicted value after forward pass: \n{y_hat}")
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error) # backward propagation
            print(f"updated weights after epoch:\n{epoch}/{self.epochs} : \n{self.weights}")
            print("#####"*10)


    def predict(self, X):
        """
        Predicts the target given an input X

        Args:
            inputs: X for predicting the y (target)

        Returns:
            0 or 1
        """
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        return self.activationFunction(X_with_bias, self.weights)

    def total_loss(self):
        """
        Calculates the cumulative loss

        Returns:
            sum of all loss
        """
        total_loss = np.sum(self.error)
        print(f"total loss: {total_loss}")
        return total_loss

def prepare_data(df):
    """
    Splits a given dataframe into X and y (target)

    Args:
        df: dataframe to be split

    Returns:
        X: the features / input
        y: the target
    """
    X = df.drop("y", axis=1)
    y = df["y"]
    return X, y

#### Create a dataframe representing the logical "AND" operation

In [8]:
"""
Truth Table of logical AND operation:
X    Y    X^Y
0    0    0
0    1    1
1    0    0
1    1    1
""";

In [17]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1],
}
df = pd.DataFrame(AND)

In [18]:
df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [10]:
X,y = prepare_data(df) # split the dataframe into X and y

ETA = 0.3 # chosen between 0 and 1
EPOCHS = 10

model = Perceptron(eta=ETA, epochs=EPOCHS)
model.fit(X, y) 
_ = model.total_loss()

initial weights before training: 
[3.71752630e-05 4.68751954e-05 2.53758750e-04]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:
0/10 : 
[ 0.30003718  0.30004688 -0.29974624]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:
1/10 : 
[3.71752630e-05 4.68751954e-05 6.00253759e-01]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:
2/10 : 
[0.30003718 0.30004688 0.30025376]
###############################

In [13]:
print(X.values)
model.predict(X)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


array([0, 0, 0, 1])

#### Create a dataframe representing the logical "OR" operation 

In [19]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,1,1,1],
}
df = pd.DataFrame(OR)

In [20]:
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [21]:
X,y = prepare_data(df) # split the dataframe into X and y

ETA = 0.3 # chosen between 0 and 1
EPOCHS = 10

model_OR = Perceptron(eta=ETA, epochs=EPOCHS)
model_OR.fit(X, y)

_ = model_OR.total_loss()

initial weights before training: 
[-1.37452853e-05 -2.00739442e-04  7.14345243e-05]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch:
0/10 : 
[ 0.59998625  0.59979926 -0.89992857]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:
1/10 : 
[ 0.59998625  0.59979926 -0.59992857]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:
2/10 : 
[ 0.59998625  0.59979926 -0.29992857]
##################################